[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "TopsCorr"
version = "0.1.0"
description = "A python package to do simple manipulation and corrections on interferograms from ISCE topsApp."
authors = [
	{name = "Chong-You (Kevin) Wang", email = "kevin11226g@gmail.com"}]
keywords = ["ISCE","topsApp","tropospheric correction","solid Earth Tide loading"]
license = "GPL-3.0" 
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy"]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/chongyouwang/TopsCorr"
Issues = "https://github.com/chongyouwang/TopsCorr/issues"
